### ISSUE TITLE
wewlad

### ISSUE THREAD

**Issue by NicoAICP** [cheuble/3DiScord-themes#1]
There are multiple reasons. First, themes provided here come from a trusted source, so you can be sure they won't do anything to your Discord account or your 3DS. Second, themes here are always updated, and will work with the latest 3DiScord version. Third, the themes provided here come as simple files you can extract to your SD without having to reinstall a CIA.

1) I don't want stuff like **tokens** from other users. That's why i said if there are problems ask you
2) I always **update** my themes too
3) I already removed the **cia** releases, only the white is in cia, didn't update it **yet**

**Comment by NicoAICP** [comment]
a **simple** JSON and a few images wont steal stuff from their accounts

**Comment by cheuble** [comment]
I wasn't specifically talking about your themes, this is a general warning if something like that ever happens, but whatever.

**Comment by Dionicio3** [comment]
gay

**Comment by NicoAICP** [comment]
How shouldn't I take it wrong, if I'm the only one (except stovven) who makes themes

**Comment by cheuble** [comment]
> If something like that ever happens.

**Comment by Kingy34** [comment]
Official > Unofficial

**Comment by Stovven** [comment]
no no, i only made it as a joke you fuck

**Comment by Dionicio3** [comment]
This is getting interesting

**Comment by NicoAICP** [comment]
> no no, i only made it as a joke you fuck
did I say you make everytime themes. I just sayed you made a theme

**Comment by cheuble** [comment]
@Dionicio3 Yes it is 🍿

**Comment by Kingy34** [comment]
I think the warning is quite nice actually. It informs the reader to use the themes that are designed/validated by the creator other than some random guy on the internet.

**Comment by cheuble** [comment]
Excuse me @Hotbrawl20 if I take the time to make proper disclaimers so I won't get in trouble *if something like that ever happens*

**Comment by ominouscheese** [comment]
Anyway you look at it, your themes are malevolent themselves

**Comment by KevinX8** [comment]
Lad nico should just stop making themes, nobody likes them and they are messing up gbatemp

**Comment by cheuble** [comment]
Please don't turn this into drama

**Comment by ominouscheese** [comment]
^
Please no drama

**Comment by Dionicio3** [comment]
Yes drama

**Comment by ominouscheese** [comment]
Kingy'd

**Comment by NicoAICP** [comment]
> Excuse me @Hotbrawl20 if I take the time to make proper disclaimers so I won't get in trouble if something like that ever happens

okay.

**Comment by Kingy34** [comment]
> okay.

Introducing the most useless post in this issue!
